source 'https://rubygems.org'

gem 'rails', '4.1.5'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

gem 'pg_search'

# gem 'bcrypt-ruby', '3.1.2'
gem 'bcrypt', '~> 3.1.7'

# gem 'protected_attributes'
# gem 'strong_parameters'
group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  # gem 'capybara'
  gem 'jasmine-rails'
  gem 'faker'
  gem 'httparty'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
