source 'https://rubygems.org'

gem 'rails', '4.1.5'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

gem 'pg_search'

gem 'bcrypt', '~> 3.1.7'


group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'capybara'
  gem 'cucumber'
  gem 'jasmine-rails'
  gem 'faker'
  gem 'httparty'
  gem 'selenium-webdriver'
end

